# Generated by Django 2.0.8 on 2018-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategoryblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategoryBlogPage'),
        ),
    ]
