# Generated by Django 2.0.8 on 2018-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180907_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
    ]
