# Generated by Django 2.0.8 on 2018-09-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180907_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories2',
            field=models.ManyToManyField(blank=True, related_name='cat', through='blog.BlogCategoryBlogPage', to='blog.BlogCategory'),
        ),
    ]
