# Generated by Django 2.0.8 on 2018-09-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_categories2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='categories2',
        ),
    ]
