# Generated by Django 2.0.8 on 2018-09-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blogpage_categories2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategoryblogpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogcategoryblogpage',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogCategoryBlogPage',
        ),
    ]
