# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
